apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP