apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer }}
#    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.ingress.kubernetes.io/limit-connections: "{{ .Values.ingress.limitConnections }}"
    nginx.ingress.kubernetes.io/limit-rpm: "{{ .Values.ingress.limitRpm }}"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 100M
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
spec:
  tls:
  - hosts:
    {{- range .Values.ingress.tlsHosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  {{- range .Values.ingress.rules }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .service.name }}
            port:
              number: {{ .service.port }}
      {{- end }}
  {{- end }}