apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp
spec:
  hosts:
  - localhost.local
  - localhost1.local
  gateways:
  - my-gateway
  http:
  - match:
    - headers:
        host:
          exact: "localhost.local"
    route:
    - destination:
        host: myapp-service
        port:
          number: 80
  - match:
    - headers:
        host:
          exact: "localhost1.local"
    route:
    - destination:
        host: myapp1-service
        port:
          number: 80