apiVersion: apps/v1
kind: Deployment
metadata:
  name: jend
  labels:
    app: jend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jend
  template:
    metadata:
      labels:
        app: jend
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins-sa
      containers:
      - name: jenkins
        image: localhost:5000/jenkins:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
        livenessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: "/login"
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-vol
          - mountPath: /var/run/docker.sock
            name: docker-socket
          # - mountPath: /var/jenkins_home/.kube/
          #   name: kubeconfig
      volumes:
      - name: jenkins-vol
        # persistentVolumeClaim:
        #   claimName: jenkins-pvc
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      # - name: kubeconfig
      #   hostPath:
      #     path: /home/yurchyn23/.kube/config
      #     type: File
