apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: jend
  type: ClusterIP
# spec:
#   ports:
#   - port: {{ .Values.port }}
#     targetPort: 8080
#     nodePort: {{ .Values.nodePort }}
#   selector:
#     app: jend
#   type: NodePort
# status:
#   loadBalancer: {}