ingress:
  name: my-ingress
  certIssuer: selfsigned-issuer
  limitConnections: 1000 # Limits
  limitRpm: 1000 # Limits
  tlsHosts:
    - localhost.jenkins.xyz
    - localhost.app.xyz
    - localhost.app1.xyz
  secretName: ssl-certificates-tls
  rules:
    - host: localhost.app.xyz
      paths:
        - path: /
          pathType: Prefix
          service:
            name: myapp-service
            port: 80
    - host: localhost.app1.xyz
      paths:
        - path: /
          pathType: Prefix
          service:
            name: myapp1-service
            port: 80
    - host: localhost.jenkins.xyz
      paths:
        - path: /
          pathType: Prefix
          service:
            name: jenkins-svc
            port: 80